<?php

/**
 * @file
 * Global pact leo module (aka Thesaurus).
 */


/**
 * Implements hook_form_FORM_ID_alter().
 */
function gpleo_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $view = $form_state->getStorage('view');

  if ($view['view']->id() == 'thesaurus') {
    $form['topics']['#prefix'] = '<div id="topic-filter-wrapper">'
      . '<div id="topic-label">' . t('Filter by topic') . '</div>'
      . '<div id="topic-selected-items-wrapper"></div>';

    $form['topics']['#suffix'] = '<div id="topic-actions">'
      . '<a id="topic-clear" href="#" class="pull-left">' . t('Clear') . '</a>'
      . '<a id="topic-apply" href="#" class="pull-right">' . t('Apply') . '</a>'
      . '</div></div>';

    $form['#attached'] = [
      'library' => ['gpleo/thesaurus'],
    ];
  }
}


/**
 * Implements hook_theme().
 */
function gpleo_theme($existing, $type, $theme, $path) {
  return [
    'gpleo_content_block_template' => [
      'template' => 'gpleo-content-block-template',
      'variables' => [
        'informea_tid' => 0,
        'term_name' => '',
        'tid' => 0,
      ],
    ],
    'gpleo_treaty_block_template' => [
      'template' => 'gpleo-treaty-block-template',
      'variables' => [
        'params' => [],
      ],
    ],
    'gpleo_decision_block_template' => [
      'template' => 'gpleo-decision-block-template',
      'variables' => [
        'params' => [],
      ],
    ],
    'gpleo_document_block_template' => [
      'template' => 'gpleo-document-block-template',
      'variables' => [
        'params' => [],
      ],
    ],
    'gpleo_goal_block_template' => [
      'template' => 'gpleo-goal-block-template',
      'variables' => [
        'params' => [],
      ],
    ],
  ];
}
