<?php

/**
 * @file
 * Global pact leo module (aka Thesaurus).
 */

use Drupal\eck\Entity\EckEntity;


/**
 * Implements hook_form_FORM_ID_alter().
 */
function gpleo_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $view = $form_state->getStorage('view');

  if ($view['view']->id() == 'thesaurus') {
    $form['topics']['#prefix'] = '<div id="topic-filter-wrapper">'
      . '<div id="topic-label">' . t('Filter by topic') . '</div>'
      . '<div id="topic-selected-items-wrapper"></div>';

    $form['topics']['#suffix'] = '<div id="topic-actions">'
      . '<a id="topic-clear" href="#" class="pull-left">' . t('Clear') . '</a>'
      . '<a id="topic-apply" href="#" class="pull-right">' . t('Apply') . '</a>'
      . '</div></div>';

    $form['#attached'] = [
      'library' => ['gpleo/thesaurus'],
    ];
  }
}

/**
 * Implements hook_node_presave().
 */
function gpleo_node_presave(\Drupal\Core\Entity\EntityInterface $node) {
  if ($node->bundle() == 'document' && !$node->isNew) {
    $thesaurus = [];
    $tags = array_column($node->field_tags->getValue(), 'target_id');
    foreach ($tags as $tag_tid) {
      $tag = EckEntity::load($tag_tid);
      if ($field_tags = $tag->field_tags->getValue()) {
        foreach ($field_tags as $field_tag) {
          $thesaurus[] = $field_tag;
        }
      }
    }
    if ($thesaurus) {
      $node->field_thesaurus = $thesaurus;
    }

  }
}


function gpleo_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  /*dpm($form['#form_id']);
  dpm($form['form_id']);*/
 /* dpm($form_state);
  dpm(array_keys($form));*/
}
