<?php

/**
 * @file
 * Contains informeasearch.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function informeasearch_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the informeasearch module.
    case 'help.page.informeasearch':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Search results from informea related functionality.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */
function informeasearch_theme($existing, $type, $theme, $path) {
  return [
    'informeasearch_item' => [
      'template' => 'informeasearch-item',
      'variables' => [
        'doc_item' => [],
      ],
    ],
  ];
}
