<?php

/**
 * @file
 * Contains gpsearch Drupal hooks.
 */

/**
 * Implements hook_theme().
 */
function gpsearch_theme($existing, $type, $theme, $path) {
  return [
    'gpsearch_block_template' => [
      'template' => 'gpsearch-block-template',
      'render element' => 'form',
      'variables' => [],
    ],
    'facets_result_item_enhanced_select' => [
      'base hook' => 'facets_result_item',
      'variables' => [
        'facet' => NULL,
        'raw_value' => '',
        'value' => '',
        'show_count' => FALSE,
        'count' => NULL,
        'is_active' => FALSE,
      ],
    ],
  ];
}
