<?php

/**
 * Initial thesaurus import from InforMEA API.
 */
function gpthesaurus_update_8001() {
  try {
    $l = new \Drupal\gpthesaurus\LEOImport();
    $terms = $l->load('https://www.informea.org/ws/leo');
    $l->import($terms);
  }
  catch (Exception $e) {
    var_dump($e);
  }
}

/**
 * Reimport all terms with their tid.
 */
function gpthesaurus_update_8002() {
  try {
    $l = new \Drupal\gpthesaurus\LEOImport();
    $terms = $l->load('https://www.informea.org/ws/leo');
    $l->import($terms);
  }
  catch (Exception $e) {
    var_dump($e);
  }
}
