<?php

/**
 * @file
 * Contains gpbase.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
/**
 * Implements hook_help().
 */
function gpbase_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gpbase module.
    case 'help.page.gpbase':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Includes basic website features') . '</p>';
      return $output;

    default:
      return '';
  }
}

/**
 * Implements hook_node_access().
 */
function gpbase_node_access(NodeInterface $node, $op, AccountInterface $account) {
  $result = AccessResult::neutral();
  if ($node->bundle() == 'report_page' && $op == 'view' && !$account->hasPermission('view report page ct')) {
    $result = AccessResult::forbidden();
  }
  return $result;
}
